apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  labels:
    type: local
    app: minio
    tier: infrastructure
spec:
  storageClassName: minio-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: '/podMount/minio'
    type: DirectoryOrCreate
