apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  labels:
    type: local
    app: postgres
    tier: infrastructure
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: '/podMount/postgres'
    type: DirectoryOrCreate
