version: '3'

services:

  Rabbitmq:
    container_name: dev_rabbitmq
    image: rabbitmq:3.7.7
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"
    volumes:
    - ../configurations/rabbitmq/local-rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ../configurations/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:15672:15672"

  RabbitmqTest:
    container_name: test_rabbitmq
    image: rabbitmq:3.7.7
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server;"
    volumes:
    - ../configurations/rabbitmq/local-rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ../configurations/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
    - "127.0.0.1:5673:5672"

  PostgreSqlTest:
    container_name: test_postgresql
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    volumes:
    - ./postgresqltest:/var/lib/postgresql
    ports:
    - "127.0.0.1:5432:5432"

  PostgreSqlDev:
    container_name: dev_postgresql
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    volumes:
    - ./postgresqldev:/var/lib/postgresql
    ports:
    - "127.0.0.1:5433:5432"

  Minio:
    container_name: dev_minio
    image: minio/minio
    command: server /data
    restart: always
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
    volumes:
    - ./minio:/data
    ports:
    - "127.0.0.1:9000:9000"

  Ganache:
    container_name: dev_ganache
    image: trufflesuite/ganache-cli
    command: --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --networkId 7777 --db /data
    restart: always
    volumes:
    - ./dev_ganache:/data
    ports:
    - "127.0.0.1:8545:8545"

  EthereumBridge:
    container_name: dev_ethereum_bridge
    image: cryptomental/ethereum-bridge
    command: -H dev_ganache:8545 -a 9 --dev
    restart: always
    links:
    - "Ganache:dev_ganache"
    depends_on:
    - Ganache
