apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-volume-claim
  labels:
    app: minio
    tier: infrastructure
spec:
  storageClassName: minio-storage
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
