apiVersion: v1
kind: PersistentVolume
metadata:
  name: ganache-pv-volume
  labels:
    type: local
    app: ganache
    tier: infrastructure
spec:
  storageClassName: ganache
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/ganache
