apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    tier: infrastructure
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-connection
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage
              subPath: postgres
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-volume-claim
