apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    tier: infrastructure
type: Opaque
data:
  # accesskey
  MINIO_ACCESS_KEY: YWNjZXNza2V5
  # secretkey
  MINIO_SECRET_KEY: c2VjcmV0a2V5
